# This file is a template, and might need editing before it works on your project.
image: node:latest

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

pages:
  script:
    - rm -rf .cache
    - rm -rf public/
    - yarn install
    - yarn build:clean
    
  artifacts:
    paths:
      - public
