---
os: linux
dist: xenial

language: node_js
node_js:
  - 12.18.4

before-install: npm i -g markdown-link-check
install:
  - yarn install
script:
  - ./node_modules/.bin/mdspell -r -n -a -x --en-us 'src/pages/**/*.mdx'
