[build]
  command = "yarn && yarn build:clean"
  base = "."
  publish = "public"
  environment = {  NODE_VERSION = "12" }

## [headers]]
  # Define which paths this specific [[headers]] block will cover.
#  for = "/*"
#  [headers.values]
#    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[context.testing]
    command = "yarn && yarn run pretest"


[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = true
[build.processing.js]
  bundle = true
  minify = true
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
