[context.production]
  command = "npm install && mpm run-script build"
  [context.production.environment]
    base = "."
    command = "npm run-script clean && mpm run-script build"
    publish = "public"
    environment = {  NODE_VERSION = "12" }

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"

[build]
    command = "npm run build"


[build.processing]
  skip_processing = false
[build.processing.css]
  bundle = true
  minify = false
[build.processing.js]
  bundle = true
  minify = false
[build.processing.html]
  pretty_urls = true
[build.processing.images]
  compress = true
