# circle-ci nodejs build 
version: 2.1

orbs:
  codecov: codecov/codecov@1.1.1
jobs:
    build:
        docker:
            - image: circleci/node:12
        working_directory: ~/gatsby-site
        steps:
            - checkout
            - restore_cache:
                  keys:
                      # Find a cache corresponding to this specific package-lock.json
                      - v1-npm-deps-{{ checksum "package-lock.json" }}
                      # Fallback cache to be used
                      - v1-npm-deps-
            - run:
                  name: Install Dependencies
                  command: npm install
            - save_cache:
                  key: v1-npm-deps-{{ checksum "package-lock.json" }}
                  paths:
                      - ./node_modules
            - run:
                  name: Gatsby Build
                  command: yarn run build
            - codecov/upload:
                  file: {{ coverage_report_filepath }}
