version: 2.1

executors:
  default:
    docker:
      - image: circleci/node:12
    working_directory: ~/gatsby-site
    environment:
      YARN_CACHE_FOLDER: "~/.cache/yarn"

commands:
  attach_gatsby:
    steps:
      - attach_workspace:
          at: ~/gatsby-site

jobs:
  install-dependencies:
    executor: default
    steps:
      - checkout
      - attach_gatsby
      - restore_cache:
          keys:
            - yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
            - yarn-packages-v1-{{ .Branch }}-
            - yarn-packages-v1-
      - run:
          name: Install gatsby dependencies
          command: npm install -g codecov && yarn install --frozen-lockfile
      - save_cache:
          key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
          paths: ~/.cache/yarn
      - persist_to_workspace:
          root: .
          paths: .

  build-packages:
    executor: default
    steps:
      - attach_gatsby
      - run:
          name: Build packages
          command: yarn add global codecov &&  yarn install 
      - run:
          name: Yarn Gatsby Build 
          command: yarn run build && codecov

workflows:
  build-and-test:
    jobs:
      - install-dependencies
      - build-packages:
          requires:
            - install-dependencies
