# circle-ci
version: 2
jobs:
  install-dependencies:
    docker:
    - image: circleci/node:12
    working_directory: ~/gatsby-site
    steps:
    - checkout
    - attach_workspace:
        at: ~/gatsby-site
    - run:
        name: Install gatsby dependencies
        command: yarn add global gatsby-cli  && yarn install
    - save_cache:
        key: yarn-packages-v1-{{ .Branch }}-{{ checksum "yarn.lock" }}
        paths: ~/.cache/yarn
    - persist_to_workspace:
        root: .
        paths: .
#    environment:
#    - YARN_CACHE_FOLDER: ~/.cache/yarn
  build-packages:
    docker:
    - image: circleci/node:12
    working_directory: ~/gatsby-site
    steps:
    - attach_workspace:
        at: ~/gatsby-site
    - run:
        name: Build packages
        command: yarn add global codecov &&  yarn install
    - run:
        name: Yarn Gatsby Build
        command: yarn run build && codecov
#    environment:
#    - YARN_CACHE_FOLDER: ~/.cache/yarn
workflows:
  build-and-test:
    jobs:
    - install-dependencies
    - build-packages:
        requires:
        - install-dependencies
